version: '3.4'

services:

  statup:
    container_name: statup
    image: sytabaresa/statping:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - database
    depends_on:
      - postgres
    volumes:
      - ./statup/app:/app
    environment:
      DB_CONN: postgres
      DB_HOST: postgres
      DB_USER: statup
      DB_PASS: zMyZug1Gf8SxQ4UAkBFRXcFodLhfjolwoTW9s2Sl
      DB_DATABASE: statup
      http_proxy: http://10.20.4.15:3128
      https_proxy: http://10.20.4.15:3128
      no_proxy: "localhost,127.0.0.0/8,::1,0.0.0.0,10.0.0.0/8"

  postgres:
    container_name: postgres
    image: postgres:10.6-alpine
    restart: always
    networks:
      - database
    volumes:
      - ./statup/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: zMyZug1Gf8SxQ4UAkBFRXcFodLhfjolwoTW9s2Sl
      POSTGRES_USER: statup
      POSTGRES_DB: statup

networks:
  database:
